/**
 * The single content source for all three variations.
 * - business.json : verified business facts (nulls render as visible placeholders)
 * - products.json : the catalog (sample prices; owner-editable)
 * - images.json   : generated by scripts/build-images.mjs
 */
import businessJson from '../content/business.json'
import productsJson from '../content/products.json'
import imagesJson from '../content/images.json'

export type Category = 'crystals' | 'minerals' | 'jewelry'

export interface Product {
  slug: string
  no: string // catalogue number (demo SKU, not a business fact)
  name: string
  category: Category
  price: number | null // null = not priced yet → shows [PLACEHOLDER: price]
  images: string[] // image names from images.json, or data:/http URLs for owner-added items
  description: string
  material: string | null
  origin: string | null
  size: string | null
  weight: string | null
  stock: number
  one_of_a_kind: boolean
  sold: boolean
  new: boolean
  featured: boolean
  tiktok: string | null
  ownerAdded?: boolean
}

export const BUSINESS = businessJson
export const BASE_PRODUCTS = productsJson.products as Product[]
export const IMAGES = imagesJson as Record<string, { w: number; h: number; widths: number[] }>

export const CATEGORIES: { id: Category; label: string; blurb: string; image: string }[] = [
  { id: 'crystals', label: 'Crystals', blurb: 'Hearts, freeforms, clusters and carvings', image: 'citrine-druzy-heart' },
  { id: 'minerals', label: 'Minerals', blurb: 'Natural specimens, as they formed', image: 'amethyst-tower' },
  { id: 'jewelry', label: 'Jewelry', blurb: 'Stones made to be worn', image: 'lapis-triple-necklace' },
]

export const ADDRESS_LINE = `${BUSINESS.address.street}, ${BUSINESS.address.city}, ${BUSINESS.address.region} ${BUSINESS.address.postal}`
export const TEL_HREF = `tel:${BUSINESS.phoneE164}`

export const money = (n: number | null | undefined) =>
  n == null ? '[PLACEHOLDER: price]' : `$${n.toLocaleString('en-US', { minimumFractionDigits: n % 1 ? 2 : 0, maximumFractionDigits: 2 })}`

/** Demo-only numbers the checkout needs. Replace with platform settings in production. */
export const DEMO = {
  shippingFlat: 15, // [PLACEHOLDER: shipping rates]
  freeShippingOver: null as number | null,
  taxRate: BUSINESS.texasSalesTaxRate, // Austin combined rate; the payment platform calculates the real figure
}
